const Theme = {
    TEXT_INPUT_ACTIVE_COLOR: '#066acf',
    TEXT_INPUT_ACTIVE_LABEL_COLOR: '#0b78e6',
    SECONDARY_TEXT_COLOR: '#8a8a8a',
    TEXT_INPUT_TEXT_COLOR: '#2b2b2b',
    TEXT_INPUT_DEFAULT_COLOR: '#8a8a8a',
    TEXT_INPUT_ERROR_COLOR: '#F56565',
    PRIMARY: '#78FFCE',
    WHITE: '#fff',
    PRIMARY_BACKGROUND_COLOR: '#2C3849',
    TEXT_COLOR: '#fff',
    PLACE_HOLDER_TEXT_COLOR: '#6D7182',
    TEXT_COLOR_DARK: '#2C3849',
    TEXT_COLOR_LIGHT: '#fff',
    WARNING: '#FF5A64',
    BORDER: '#647387',
} as const;

export default Theme;
